import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { getServerClient } from "@/lib/server/supabase";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await getServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="px-6 sm:px-10 py-4 border-b border-foreground/10">
          <div className="max-w-6xl mx-auto flex items-center justify-between">
            <Link href="/" className="font-semibold">MoisoTalk</Link>
            <nav className="flex items-center gap-3 sm:gap-4 text-sm">
              {user ? (
                <Link
                  href="/me"
                  className="px-3 py-2 rounded border border-foreground/20 hover:bg-foreground/10 transition"
                >
                  마이페이지
                </Link>
              ) : (
                <>
                  <Link
                    href="/login"
                    className="px-3 py-2 rounded border border-foreground/20 hover:bg-foreground/10 transition"
                  >
                    로그인
                  </Link>
                  <Link
                    href="/signup"
                    className="px-4 py-2 rounded bg-foreground text-background hover:opacity-90 transition"
                  >
                    회원가입
                  </Link>
                </>
              )}
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
